site_name: My Project Documentation
nav:
  - Home: index.md
  - rules: code_rules.md
  - API Reference: api.md
theme: readthedocs
# Define markdown extensions (optional)
markdown_extensions:
  - toc:
      permalink: true

# Set paths for documentation
docs_dir: docs
site_dir: site

# Plugins and other MkDocs extensions can be added here
